dist: xenial
sudo: false
language: php

install:
- phpenv config-rm xdebug.ini || return 0
# todo-sg: need to install magento2 to run tests as it uses the bootstrap file in dev folder
#- echo "{\"http-basic\":{\"repo.magento.com\":{\"username\":\"${MAGENTO_USERNAME}\",\"password\":\"${MAGENTO_PASSWORD}\"}}}" > auth.json
#- if [[ "$MAGENTO_USERNAME" ]]; then composer install ; fi
php:
  - '7.1'
  - '7.2'

script:
  - curl -L https://cs.symfony.com/download/php-cs-fixer-v2.phar -o php-cs-fixer
  - chmod a+x php-cs-fixer
  - git checkout -B $TRAVIS_BRANCH
  - ./php-cs-fixer fix --config=.php-cs.dist --cache-file=.php-cs.cache --diff --dry-run --verbose
  - rm php-cs-fixer
jobs:
  include:
  - stage: deploy
    php: '7.1'
    before_script: skip
    script:
    - if [[ "$TRAVIS_TAG" ]]; then
        chmod +x ./release/build_release_package.sh;
        ./release/build_release_package.sh;
      fi
    deploy:
      provider: releases
      api_key: ${GITHUB_TOKEN}
      file: shopgate-base-${TRAVIS_TAG}.zip
      skip_cleanup: true
      on:
        tags: true

notifications:
  slack:
    rooms:
      secure: mfCzFCn4+YP6Vh9/VVRgxUg178mcZtn+LyWmLu1DyFQOG/0JBcgbE4hAba6Fll2BbGvk29nckMsKsKzeydSjGCVAUu8N9LVAg3ZaszdIXZUZB9r56F/T/cyFm2O/n8xTBJIX+CRE94YSUcyocW/oERROlmrb7oWIQKYlHugAKAvOY5bC/SemxYl7HLoLHgra8JMqzpaxOtjt/jf9YVxcJafT8psQGzZ0sd3jiy1KHXjTpSblS+O2K110bCp6vGlRIM70bjXjZlvqex5yMg3oASIgIFtWuRkWH1ZwfPlPVYUd53ghq3K0vKG4/BOZ1T+6fTHbLwdiJUrkOMlHbheRPnTgKgBiQt9Gkqi04lXjv7aiYrWq4Tb222PTydytRpesSkmJPiXmtcKFUYsKvYA/ZzeBSRBDgxXlG4maCzEJALqiMgWRNL8DbzmMJ8qyzG56LHdQ+zhsWmY63yvVRxEtOX1LwMEjAJV1n1PQIVC1Yu61o1xO2uRonLwtlSj0a4oSn9Ftz7rAw36RguXUvX+4uOXRL2Hou3Jp5Piybn4NI7dnCZCrFlHY0CX/8CaerFDGVeQkpjUotUte92/VVkE4T8oL2kE/v64Wbw1RVZnFfX5gm7TWBf4Kxyu5l2RpcpkGlzC0YPXiEtLdsiRl4o47EmU1eZfqFEVgQIjqqfJQS9Y=
    on_success: change
    on_failure: always
